name: DeploySageMakerModel

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  SAGEMAKER_PROJECT_NAME: sagemaker-github
  EXPORT_TEMPLATE_STAGING_CONFIG: "staging-config-export.json"
  EXPORT_TEMPLATE_PROD_CONFIG: "prod-config-export.json"

jobs:
  StagingDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip botocore boto3 awscli

      - name: Test Staging
        run: | 
          echo "Test Staging... This will take about a few seconds."
          echo "No issues found."

  ProductionDeploy:
    needs: StagingDeploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Setup python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip botocore boto3 awscli
