name: Deploy

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-west-2
  STAGING_PARAMS_FILE: staging_params.json
  STAGING_TAGS_FILE: staging_tags.json
  PRODUCTION_PARAMS_FILE: production_params.json
  PRODUCTION_TAGS_FILE: production_tags.json

jobs:
  stagingdeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run build_deployment_configs.py
        run: |
          python build_deployment_configs.py

      - name: Save configs to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: staging-configs
          path: |
            ${{ env.STAGING_PARAMS_FILE }}
            ${{ env.STAGING_TAGS_FILE }}

      - name: Deploy to staging
        run: |
          python deploy_stack.py --params ${{ env.STAGING_PARAMS_FILE }} --tags ${{ env.STAGING_TAGS_FILE }}

  productiondeploy:
    runs-on: ubuntu-latest
    needs: stagingdeploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download staging configs
        uses: actions/download-artifact@v4.1.7
        with:
          name: staging-configs
          path: .

      - name: Deploy to production
        run: |
          python deploy_stack.py --params ${{ env.PRODUCTION_PARAMS_FILE }} --tags ${{ env.PRODUCTION_TAGS_FILE }}
